### ISSUE TITLE
buildAccountStatsRequest() doesn't work

### ISSUE THREAD

**Issue by dimapasko** [fullcontact/fullcontact4j#20]
Hi 

I'm using *fullcontact4j*
In following way:

        FullContact fullContact = FullContact.withApiKey(fullContactKey).build();
        AccountStatsRequest accountStatsRequest = fullContact.buildAccountStatsRequest().setPeriod(2015, 1).build();

where `fullContactKey` is correct API key

For 
`AccountStatsResponse accountStatsResponse = fullContact.sendRequest(accountStatsRequest);`

I'm getting following error:

    com.fullcontact.api.libs.fullcontact4j.FullContactException: Invalid period; YYYY-MM format expected
    com.fullcontact.api.libs.fullcontact4j.http.FCRetrofitCallback.failure(FCRetrofitCallback.java:69)
    at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
    at retrofit.Utils$SynchronousExecutor.execute(Utils.java:114)
    at retrofit.CallbackRunnable.run(CallbackRunnable.java:51)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at retrofit.Platform$Base$2$1.run(Platform.java:94)

In debbuger i found out that *fullcontact4j*  actually calls `https://api.fullcontact.com/v2/stats.json?period=2015-1` without `apiKey`

It seems that `fullContact.buildAccountStatsRequest()` doesn't work fine :(

Let me know if i missed something.

Thank you!

**Comment by eentzel** [comment]
Thanks @dimapasko! We will get a fixed version released shortly.

**Comment by dimapasko** [comment]
@eentzel Great, Thx!

**Comment by dimapasko** [comment]
@eentzel @ParisMi 
Could you provide version number as soon as it would be available on bitray, please?

**Comment by ParisMi** [comment]
should be up there now, 2.1.3.

**Comment by dimapasko** [comment]
Thx, it works now :+1:
