### ISSUE TITLE
No Manifest file

### ISSUE THREAD

**Issue by ashishparmar** [fullcontact/fullcontact4j#27]
How can use this , Because of not any manifest file available?

Can you please release jar file instead of this type of structure sdk.

**Comment by ParisMi** [comment]
Hey there, 

this repository is only for the source code for fullcontact4j. The actual JAR file is hosted on Bintray. You can use maven or gradle if your project supports it by following the instructions in the [readme](https://github.com/fullcontact/fullcontact4j/blob/master/README.md) under "add to your project".

If you would like the JAR file by itself, you can download it from [here](http://dl.bintray.com/fullcontact/fullcontact-oss/com/fullcontact/fullcontact4j/2.5.1/).
