### ISSUE TITLE
Usage limits for the provided API Key have been exceeded

### ISSUE THREAD

**Issue by sid180** [fullcontact/fullcontact4j#51]
Hi,
I have Implemented, a trial version  FullContact API in my project. I got the following exception with in my first call itself. 
com.fullcontact.api.libs.fullcontact4j.FullContactException: Usage limits for the provided API Key have been exceeded. Please try again later or contact support to increase your limits.
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at com.fullcontact.api.libs.fullcontact4j.http.FCRetrofitCallback.failure(FCRetrofitCallback.java:80)
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at retrofit.Utils$SynchronousExecutor.execute(Utils.java:114)
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at retrofit.CallbackRunnable.run(CallbackRunnable.java:51)
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err: Caused by: retrofit.RetrofitError: 403 Forbidden
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:383)
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
06-19 16:32:22.762 6646-6646/com.example.ebms.myapplication W/System.err:     at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)

**Comment by ParisMi** [comment]
Hey Sid, go to the developer portal (portal.fullcontact.com) and look at your remaining usage on your api key. Make sure you still have requests remaining there. If your API key looks OK, please email support@fullcontact.com so we can help you figure out your problem in detail. Thanks!
