### ISSUE TITLE
Card Reader - Stream Support

### ISSUE THREAD

**Issue by jimhooker2002** [fullcontact/fullcontact4j#52]
Uploading a card currently takes an InputStream for the frontPhoto.  Under the hood, it then copies this into a string before sending it to the server.  

It should be possible using Retrofit's multi-part upload support to stream the file through rather than  first copying it into a String.

The reason I care about this is because it has the potential to chew up a lot of memory on my server having all of these images in memory.

**Comment by ParisMi** [comment]
@jimhooker2002  how does https://github.com/fullcontact/fullcontact4j/pull/53 look to you?

**Comment by jimhooker2002** [comment]
Thank you for the fast turn-around.  I'm testing with it now.  Let ya know.

**Comment by jimhooker2002** [comment]
Added a comment.  I'll reproduce here for ease of reference:

"encodeToStringAndClose is the method I was originally concerned with. This turns the stream into a string in memory. I'm hoping there's a way to send the stream through Retrofit without turning it into a String. The String inhales the file into memory which is a potential scaling problem. Really I'd like the library to work with the stream throughout. Wanted cardFront to take an InputStream which is then streamed through Retrofit and onto FullContact - all without inhaling stream into a String in memory."

The "File" code isn't actually useful to me.  I download the image on my end from another server that gives me the data as a stream.  I want to avoid loading this into memory as a String.   fullcontact4j accepts the stream and then turns it into String and consumes memory.  Really, I'd like the stream to be used throughout the fullcontact4j library and handed onto your service (stream all the way - no String in memory).

**Comment by jimhooker2002** [comment]
I quickly sketched out the following to give an idea of how I'm thinking (no clue if it works, just hoping it will illustrate how I'm thinking).  Note that photo is never pulled into a String, always handled as a stream.

import okhttp3.MediaType;
import okhttp3.RequestBody;
import okio.BufferedSink;
import retrofit.http.Multipart;
import retrofit.http.POST;
import retrofit.http.Part;

import java.io.IOException;
import java.io.InputStream;

public class StreamingExample {

    private StreamingRetrofit streamingRetrofit;

    public void uploadStream(InputStream photoStream) {
        StreamingRequestBody streamingRequestBody
                = new StreamingRequestBody(MediaType.parse("SOME MEDIA TYPE HERE"), photoStream);
        streamingRetrofit.uploadCard(streamingRequestBody);
    }

    private class StreamingRequestBody extends RequestBody {

        private MediaType mediaType;
        private InputStream inputStream;

        public StreamingRequestBody(MediaType mediaType, InputStream inputStream) {
            this.mediaType = mediaType;
            this.inputStream = inputStream;
        }

        @Override
        public MediaType contentType() {
           return mediaType;
        }

        @Override
        public void writeTo(BufferedSink bufferedSink) throws IOException {
            int byteToWrite;
            while ((byteToWrite = inputStream.read()) != -1) {
                bufferedSink.writeByte(byteToWrite);
            }
        }
    }

    private interface StreamingRetrofit {

        @Multipart
        @POST("/some/endpoint")
        public void uploadCard(@Part("front") RequestBody requestBodyFront);

    }

}

**Comment by ParisMi** [comment]
Do the latest commits on https://github.com/fullcontact/fullcontact4j/pull/53 address your needs?

**Comment by jimhooker2002** [comment]
@ParisMi thank you! That looks good.
