### ISSUE TITLE
fullcontact4j -> Maven Central.

### ISSUE THREAD

**Issue by jimhooker2002** [fullcontact/fullcontact4j#54]
I know the client jar is published to Bintray, this actually makes it difficult to consume.

Large companies typically hide their build system under layers of abstraction that aren't easy to get changed by developers within it.  Typically those companies know about Maven, but not Bintray.

That's certainly the position I've found myself in a number of times at various companies.  In order to consume the current jar, I need to download it and go through a bunch of bureaucracy to store it in some special third-party repo within our build system.  If it were in Maven Central then it would all "just work".

Please can we get the client jar published to Maven Central.  Practically every Java development environment/build-system on that planet knows how to work with that.  That's not the case for Bintray.

**Comment by ParisMi** [comment]
Marking this closed due to inactivity (and changing requirements)
