### ISSUE TITLE
Dependency Cleanup

### ISSUE THREAD

**Issue by jimhooker2002** [fullcontact/fullcontact4j#55]
This file contains quite a lot of dependencies: https://github.com/fullcontact/fullcontact4j/blob/master/pom.xml

Retrofit itself is fairly heavy-weight.  Many systems already use those libraries with different versions.  I've had to exclude all of the transitive dependencies in order to avoid conflicts.

Would you consider either using <scope>optional</scope> or splitting this package apart in order to give us better control over dependencies.

Using optional scope is the easiest thing to do.

**Comment by ParisMi** [comment]
>If a user wants to use functionality related to an optional dependency, they will have to redeclare that optional dependency in their own project.

That seems like an undue burden on the "plug and play" users. It's unfortunate the client has the dependency footprint it does but I'm not sure it makes sense to force all users to have to think about excludes/optionals/missing deps at runtime.

**Comment by ParisMi** [comment]
Marking this closed due to inactivity -- please open a new issue if this comes up again.
