### ISSUE TITLE
Organization serialization issue

### ISSUE THREAD

**Issue by xjodoin** [fullcontact/fullcontact4j#57]
When I serialized com.fullcontact.api.libs.fullcontact4j.http.person.model.Organization I should get 

{"name":"test","startDate":null,"current":true,"endDate":null,"title":null,"isPrimary":true}

And I got this :
{"name":"test","startDate":null,"current":true,"endDate":null,"title":null,"isPrimary":true,"primary":true}

@Test
  public void testOrganisationSerialization() throws JsonProcessingException {
    Organization organization = new Organization("test", null, true, null, null, true);
    String actual = new ObjectMapper().writeValueAsString(organization);
    assertEquals("{\"name\":\"test\",\"startDate\":null,\"current\":true,\"endDate\":null,\"title\":null,\"isPrimary\":true}", actual);
  }

**Comment by ParisMi** [comment]
Yep, odd. Looks like Jackson gets a bit too clever serializing boolean property names. https://github.com/fullcontact/fullcontact4j/pull/58 should fix your issue, deploying as 5.4.1 shortly.

**Comment by ParisMi** [comment]
Thanks for the bug report!
